name: BBM Horusec Security Check
run-name: BBM Horusec Security Check
on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]

jobs:
  Horusec-Code-Scanning:
    name: Horusec Security
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with: 
        fetch-depth: 0

    - name: Running Horusec Security
      run: |
        curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
        horusec start -p="./" -e="true" 